# Generated by Django 4.2.8 on 2025-11-17 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stocks', '0002_add_shares_outstanding'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='통장명')),
                ('category', models.CharField(max_length=50, verbose_name='카테고리')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='현재 잔액')),
                ('total_deposited', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='총 입금액')),
                ('monthly_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='월 예산')),
                ('current_month_spent', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='이번 달 사용액')),
                ('total_savings_reward', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='총 절약 리워드')),
                ('pending_reward', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='대기 중인 리워드')),
                ('realized_reward', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='실현된 리워드')),
                ('auto_sync_enabled', models.BooleanField(default=False, verbose_name='자동 동기화 활성화')),
                ('sync_category_rules', models.JSONField(blank=True, default=dict, verbose_name='카테고리 매핑 규칙')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '카테고리 통장',
                'verbose_name_plural': '카테고리 통장',
                'db_table': 'category_accounts',
            },
        ),
        migrations.CreateModel(
            name='DepositAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=50, unique=True, verbose_name='계좌번호')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='예치금 잔액')),
                ('total_deposited', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='총 입금액')),
                ('total_withdrawn', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='총 출금액')),
                ('alpaca_account_id', models.CharField(blank=True, max_length=100, verbose_name='Alpaca 계좌 ID')),
                ('bank_account_number', models.CharField(blank=True, max_length=100, verbose_name='은행 계좌번호')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '예치금 계좌',
                'verbose_name_plural': '예치금 계좌',
                'db_table': 'deposit_accounts',
            },
        ),
        migrations.CreateModel(
            name='UserBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plaid_access_token', models.CharField(max_length=200)),
                ('plaid_item_id', models.CharField(max_length=100)),
                ('plaid_account_id', models.CharField(max_length=100)),
                ('bank_name', models.CharField(max_length=200)),
                ('account_name', models.CharField(max_length=200)),
                ('account_type', models.CharField(max_length=50)),
                ('account_number_masked', models.CharField(max_length=20)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('available_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '은행 계좌',
                'verbose_name_plural': '은행 계좌',
                'db_table': 'user_bank_accounts',
                'unique_together': {('user', 'plaid_account_id')},
            },
        ),
        migrations.CreateModel(
            name='SavingsReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('savings_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='절약 금액')),
                ('period_start', models.DateField(verbose_name='기간 시작일')),
                ('period_end', models.DateField(verbose_name='기간 종료일')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='예산')),
                ('actual_spent', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='실제 사용액')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='매수 가격')),
                ('purchase_date', models.DateTimeField(verbose_name='매수 일시')),
                ('shares', models.DecimalField(decimal_places=6, max_digits=15, verbose_name='매수 주수')),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='현재가')),
                ('current_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='현재 가치')),
                ('return_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='수익률 (%)')),
                ('is_profitable', models.BooleanField(default=False, verbose_name='수익 상태')),
                ('can_sell', models.BooleanField(default=False, verbose_name='매도 가능 여부')),
                ('sell_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='매도 가격')),
                ('sell_date', models.DateTimeField(blank=True, null=True, verbose_name='매도일')),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='수수료')),
                ('net_proceeds', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='순수익')),
                ('status', models.CharField(choices=[('pending', '대기 중'), ('invested', '투자 중'), ('sold', '매도 완료'), ('locked', '보유 강제')], default='pending', max_length=20, verbose_name='상태')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_rewards', to='accounts.categoryaccount')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='savings_investments', to='stocks.stock')),
            ],
            options={
                'verbose_name': '절약 리워드',
                'verbose_name_plural': '절약 리워드',
                'db_table': 'savings_rewards',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DepositTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('deposit', '입금'), ('withdrawal', '출금'), ('investment', '투자'), ('sale', '매도')], max_length=20, verbose_name='거래 유형')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='금액')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='거래 후 잔액')),
                ('note', models.TextField(blank=True, verbose_name='메모')),
                ('transaction_date', models.DateTimeField(auto_now_add=True, verbose_name='거래일시')),
                ('deposit_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.depositaccount', verbose_name='예치금 계좌')),
            ],
            options={
                'verbose_name': '예치금 거래',
                'verbose_name_plural': '예치금 거래',
                'db_table': 'deposit_transactions',
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.AddField(
            model_name='categoryaccount',
            name='linked_bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_accounts', to='accounts.userbankaccount', verbose_name='연동된 은행 계좌'),
        ),
        migrations.AddField(
            model_name='categoryaccount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('deposit', '입금'), ('withdrawal', '출금'), ('reward', '리워드'), ('investment', '투자'), ('sale', '매도'), ('bank_sync', '은행 동기화')], max_length=20, verbose_name='거래 유형')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='금액')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='거래 후 잔액')),
                ('merchant_name', models.CharField(blank=True, max_length=200, verbose_name='가맹점명')),
                ('category_detail', models.CharField(blank=True, max_length=100, verbose_name='카테고리 상세')),
                ('plaid_transaction_id', models.CharField(blank=True, max_length=100, verbose_name='Plaid 거래 ID')),
                ('bank_transaction_id', models.CharField(blank=True, max_length=100, verbose_name='은행 거래 ID')),
                ('is_synced_from_bank', models.BooleanField(default=False, verbose_name='은행 동기화 여부')),
                ('note', models.TextField(blank=True, verbose_name='메모')),
                ('transaction_date', models.DateTimeField(auto_now_add=True, verbose_name='거래일시')),
                ('bank_transaction_date', models.DateTimeField(blank=True, null=True, verbose_name='은행 거래일시')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.categoryaccount')),
            ],
            options={
                'verbose_name': '거래 내역',
                'verbose_name_plural': '거래 내역',
                'db_table': 'transactions',
                'ordering': ['-transaction_date'],
                'indexes': [models.Index(fields=['plaid_transaction_id'], name='transaction_plaid_t_3baf81_idx'), models.Index(fields=['is_synced_from_bank'], name='transaction_is_sync_a30559_idx')],
            },
        ),
        migrations.AlterUniqueTogether(
            name='categoryaccount',
            unique_together={('user', 'category')},
        ),
    ]
