# Generated by Django 4.2.8 on 2025-11-17 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='bank_transaction_date',
            field=models.DateField(blank=True, null=True, verbose_name='은행 거래일시'),
        ),
    ]
