# Generated by Django 4.2.11 on 2026-01-04 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_add_is_simulation_to_user_bank_account"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userbankaccount",
            name="is_simulation",
            field=models.BooleanField(default=False),
        ),
    ]
