# Generated by Django 4.2.11 on 2025-11-03 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("stocks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Watchlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("memo", models.TextField(blank=True, null=True, verbose_name="메모")),
                (
                    "preferred_mate",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="선호 메이트"
                    ),
                ),
                (
                    "is_holding",
                    models.BooleanField(default=False, verbose_name="보유 여부"),
                ),
                (
                    "purchase_date",
                    models.DateField(blank=True, null=True, verbose_name="매수일"),
                ),
                (
                    "purchase_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="매수가",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="보유 수량"
                    ),
                ),
                (
                    "alert_enabled",
                    models.BooleanField(default=True, verbose_name="알림 활성화"),
                ),
                (
                    "alert_gap_ratio",
                    models.DecimalField(
                        decimal_places=2,
                        default=-10,
                        help_text="적정가 대비 괴리율이 이 값 이하일 때 알림 (예: -10%)",
                        max_digits=5,
                        verbose_name="알림 괴리율",
                    ),
                ),
                (
                    "added_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="추가일"),
                ),
                (
                    "last_checked_at",
                    models.DateTimeField(auto_now=True, verbose_name="마지막 확인"),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watchers",
                        to="stocks.stock",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watchlist",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "관심 종목",
                "verbose_name_plural": "관심 종목",
                "db_table": "watchlist",
                "indexes": [
                    models.Index(
                        fields=["user", "added_at"], name="watchlist_user_id_232a00_idx"
                    )
                ],
                "unique_together": {("user", "stock")},
            },
        ),
    ]
