# Generated by Django 4.2.11 on 2025-11-07 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("stocks", "0002_add_shares_outstanding"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="카테고리명"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=100, unique=True, verbose_name="슬러그"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                ("order", models.IntegerField(default=0, verbose_name="순서")),
                ("is_active", models.BooleanField(default=True, verbose_name="활성화")),
            ],
            options={
                "verbose_name": "콘텐츠 카테고리",
                "verbose_name_plural": "콘텐츠 카테고리",
                "db_table": "content_categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ContentSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="소스명"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=100, unique=True, verbose_name="슬러그"
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("youtube", "유튜브 채널"),
                            ("platform", "강의 플랫폼"),
                            ("newsletter", "뉴스레터"),
                            ("blog", "블로그"),
                            ("report", "리포트"),
                            ("our_content", "자체 콘텐츠"),
                        ],
                        max_length=20,
                        verbose_name="소스 타입",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                ("website", models.URLField(blank=True, verbose_name="웹사이트")),
                ("logo_url", models.URLField(blank=True, verbose_name="로고 URL")),
                ("is_free", models.BooleanField(default=True, verbose_name="무료")),
                (
                    "price_info",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="가격 정보"
                    ),
                ),
                (
                    "quality_rating",
                    models.IntegerField(
                        default=5, help_text="1-5점", verbose_name="품질 평가"
                    ),
                ),
                (
                    "reliability",
                    models.IntegerField(
                        default=5, help_text="1-5점", verbose_name="신뢰도"
                    ),
                ),
                (
                    "target_audience",
                    models.CharField(blank=True, max_length=100, verbose_name="대상"),
                ),
                (
                    "specialty",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="전문 분야"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성화")),
                ("order", models.IntegerField(default=0, verbose_name="순서")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
            ],
            options={
                "verbose_name": "콘텐츠 소스",
                "verbose_name_plural": "콘텐츠 소스",
                "db_table": "content_sources",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="CuratedContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                ("description", models.TextField(verbose_name="설명")),
                ("url", models.URLField(verbose_name="링크")),
                ("thumbnail", models.URLField(blank=True, verbose_name="썸네일")),
                (
                    "creator",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="작성자/채널"
                    ),
                ),
                (
                    "duration",
                    models.CharField(
                        blank=True,
                        help_text="예: 45분, 1시간 20분",
                        max_length=50,
                        verbose_name="길이",
                    ),
                ),
                (
                    "difficulty",
                    models.IntegerField(
                        choices=[
                            (1, "⭐ 입문"),
                            (2, "⭐⭐ 초급"),
                            (3, "⭐⭐⭐ 중급"),
                            (4, "⭐⭐⭐⭐ 고급"),
                            (5, "⭐⭐⭐⭐⭐ 전문가"),
                        ],
                        default=2,
                        verbose_name="난이도",
                    ),
                ),
                (
                    "tags",
                    models.JSONField(blank=True, default=list, verbose_name="태그"),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=0,
                        help_text="높을수록 먼저 표시",
                        verbose_name="우선순위",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="추천"),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=False, help_text="종목 이해에 필수", verbose_name="필수"
                    ),
                ),
                (
                    "curator_note",
                    models.TextField(
                        blank=True,
                        help_text="왜 이 콘텐츠를 추천하는지",
                        verbose_name="큐레이터 노트",
                    ),
                ),
                ("views", models.IntegerField(default=0, verbose_name="조회수")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contents",
                        to="content.contentcategory",
                        verbose_name="카테고리",
                    ),
                ),
                (
                    "recommended_for_stocks",
                    models.ManyToManyField(
                        blank=True,
                        related_name="recommended_contents",
                        to="stocks.stock",
                        verbose_name="추천 종목",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contents",
                        to="content.contentsource",
                        verbose_name="콘텐츠 소스",
                    ),
                ),
            ],
            options={
                "verbose_name": "큐레이션 콘텐츠",
                "verbose_name_plural": "큐레이션 콘텐츠",
                "db_table": "curated_contents",
                "ordering": ["-priority", "-is_featured", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WeeklyBrief",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_number", models.IntegerField(verbose_name="주차")),
                ("year", models.IntegerField(verbose_name="연도")),
                ("start_date", models.DateField(verbose_name="시작일")),
                ("end_date", models.DateField(verbose_name="종료일")),
                ("market_summary", models.TextField(verbose_name="시장 요약")),
                (
                    "key_events",
                    models.JSONField(default=list, verbose_name="주요 이벤트"),
                ),
                (
                    "sector_performance",
                    models.JSONField(default=dict, verbose_name="섹터별 수익률"),
                ),
                (
                    "next_week_watch",
                    models.TextField(verbose_name="다음 주 관전 포인트"),
                ),
                (
                    "recommended_actions",
                    models.TextField(blank=True, verbose_name="추천 액션"),
                ),
                (
                    "risk_alerts",
                    models.TextField(blank=True, verbose_name="리스크 알림"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="발행됨"),
                ),
                (
                    "published_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="발행일"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "recommended_contents",
                    models.ManyToManyField(
                        blank=True,
                        related_name="weekly_briefs",
                        to="content.curatedcontent",
                        verbose_name="추천 콘텐츠",
                    ),
                ),
            ],
            options={
                "verbose_name": "주간 브리핑",
                "verbose_name_plural": "주간 브리핑",
                "db_table": "weekly_briefs",
                "ordering": ["-year", "-week_number"],
                "unique_together": {("year", "week_number")},
            },
        ),
        migrations.AddIndex(
            model_name="curatedcontent",
            index=models.Index(
                fields=["source"], name="curated_con_source__32e453_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="curatedcontent",
            index=models.Index(
                fields=["-priority", "-is_featured"],
                name="curated_con_priorit_b65dff_idx",
            ),
        ),
    ]
