# Generated by Django 4.2.11 on 2025-11-03 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("stocks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProperPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mate_type",
                    models.CharField(max_length=50, verbose_name="메이트 타입"),
                ),
                (
                    "proper_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="적정가"
                    ),
                ),
                (
                    "current_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="현재가"
                    ),
                ),
                (
                    "gap_ratio",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="%",
                        max_digits=5,
                        verbose_name="괴리율",
                    ),
                ),
                (
                    "calculation_method",
                    models.CharField(max_length=100, verbose_name="계산 방법"),
                ),
                (
                    "recommended_period_days",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="추천 투자 기간(일)"
                    ),
                ),
                (
                    "expected_return",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="예상 수익률",
                    ),
                ),
                (
                    "success_probability",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="수익 확률",
                    ),
                ),
                (
                    "calculated_at",
                    models.DateTimeField(auto_now=True, verbose_name="계산 일시"),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proper_prices",
                        to="stocks.stock",
                    ),
                ),
            ],
            options={
                "verbose_name": "적정가",
                "verbose_name_plural": "적정가",
                "db_table": "proper_prices",
                "indexes": [
                    models.Index(
                        fields=["stock", "gap_ratio"],
                        name="proper_pric_stock_i_db8a18_idx",
                    )
                ],
                "unique_together": {("stock", "mate_type")},
            },
        ),
        migrations.CreateModel(
            name="MateAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mate_type",
                    models.CharField(
                        choices=[
                            ("benjamin", "벤저민"),
                            ("fisher", "피셔"),
                            ("greenblatt", "그린블라트"),
                            ("lynch", "린치"),
                        ],
                        max_length=50,
                        verbose_name="메이트 타입",
                    ),
                ),
                ("score", models.IntegerField(help_text="0-100", verbose_name="점수")),
                (
                    "summary",
                    models.CharField(max_length=200, verbose_name="한 줄 요약"),
                ),
                ("reason", models.TextField(verbose_name="평가 이유")),
                (
                    "caution",
                    models.TextField(blank=True, null=True, verbose_name="주의사항"),
                ),
                (
                    "score_detail",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="세부 점수"
                    ),
                ),
                (
                    "analyzed_at",
                    models.DateTimeField(auto_now=True, verbose_name="분석 일시"),
                ),
                (
                    "analysis_version",
                    models.CharField(
                        default="1.0", max_length=20, verbose_name="분석 버전"
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mate_analyses",
                        to="stocks.stock",
                    ),
                ),
            ],
            options={
                "verbose_name": "메이트 분석",
                "verbose_name_plural": "메이트 분석",
                "db_table": "mate_analyses",
                "indexes": [
                    models.Index(
                        fields=["stock", "mate_type"],
                        name="mate_analys_stock_i_45cdc7_idx",
                    ),
                    models.Index(fields=["score"], name="mate_analys_score_46b22b_idx"),
                ],
                "unique_together": {("stock", "mate_type")},
            },
        ),
    ]
