# Generated by Django 4.2.8 on 2025-11-06 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mateanalysis',
            name='mate_type',
            field=models.CharField(choices=[('benjamin', '베니 (Benny)'), ('fisher', '그로우 (Grow)'), ('greenblatt', '매직 (Magic)'), ('lynch', '데일리 (Daily)')], max_length=50, verbose_name='메이트 타입'),
        ),
        migrations.CreateModel(
            name='QualitativeAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_model_type', models.CharField(max_length=200, verbose_name='비즈니스 모델 타입')),
                ('business_description', models.TextField(verbose_name='비즈니스 설명')),
                ('understandability_score', models.IntegerField(help_text='1-10', verbose_name='이해도 점수')),
                ('understandability_reason', models.TextField(verbose_name='이해도 이유')),
                ('moat_strength', models.CharField(max_length=50, verbose_name='Moat 강도')),
                ('moat_sustainability', models.IntegerField(help_text='1-10', verbose_name='Moat 지속성')),
                ('moat_factors', models.JSONField(default=list, verbose_name='Moat 요소들')),
                ('overall_risk_level', models.CharField(max_length=20, verbose_name='종합 리스크 수준')),
                ('risk_score', models.IntegerField(help_text='0-100, 높을수록 위험', verbose_name='리스크 점수')),
                ('top_risks', models.JSONField(default=list, verbose_name='주요 리스크')),
                ('investment_score', models.IntegerField(help_text='0-100', verbose_name='투자 매력도 점수')),
                ('investment_grade', models.CharField(max_length=5, verbose_name='투자 등급')),
                ('strengths', models.JSONField(default=list, verbose_name='강점')),
                ('weaknesses', models.JSONField(default=list, verbose_name='약점')),
                ('sustainability_score', models.IntegerField(default=0, help_text='1-10', verbose_name='지속가능성 점수')),
                ('analyzed_by', models.CharField(default='Claude AI', max_length=100, verbose_name='분석자')),
                ('analyzed_at', models.DateTimeField(auto_now=True, verbose_name='분석 일시')),
                ('analysis_version', models.CharField(default='1.0', max_length=20, verbose_name='분석 버전')),
                ('stock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qualitative_analysis', to='stocks.stock')),
            ],
            options={
                'verbose_name': '정성적 분석',
                'verbose_name_plural': '정성적 분석',
                'db_table': 'qualitative_analyses',
            },
        ),
    ]
