# Generated by Django 4.2.11 on 2025-11-06 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0001_initial"),
        ("analysis", "0002_alter_mateanalysis_mate_type_qualitativeanalysis"),
    ]

    operations = [
        migrations.CreateModel(
            name="TenKInsight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filing_date", models.DateField(verbose_name="Filing 일자")),
                ("fiscal_year", models.IntegerField(verbose_name="회계연도")),
                (
                    "product_revenue",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="제품별 매출"
                    ),
                ),
                (
                    "geographic_revenue",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="지역별 매출"
                    ),
                ),
                (
                    "gross_margin",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="매출총이익률",
                    ),
                ),
                (
                    "operating_margin",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="영업이익률",
                    ),
                ),
                (
                    "net_margin",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="순이익률",
                    ),
                ),
                (
                    "rd_investment",
                    models.BigIntegerField(
                        help_text="Millions", null=True, verbose_name="R&D 투자"
                    ),
                ),
                (
                    "rd_as_pct_revenue",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="R&D 비중",
                    ),
                ),
                (
                    "new_risks",
                    models.JSONField(
                        blank=True, default=list, verbose_name="신규 리스크"
                    ),
                ),
                (
                    "key_changes",
                    models.JSONField(
                        blank=True, default=list, verbose_name="주요 변화"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tenk_insights",
                        to="stocks.stock",
                    ),
                ),
            ],
            options={
                "verbose_name": "10-K 인사이트",
                "verbose_name_plural": "10-K 인사이트",
                "db_table": "tenk_insights",
                "indexes": [
                    models.Index(
                        fields=["stock", "-fiscal_year"],
                        name="tenk_insigh_stock_i_80f035_idx",
                    )
                ],
                "unique_together": {("stock", "fiscal_year")},
            },
        ),
    ]
