# Generated by Django 4.2.11 on 2025-11-07 11:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0002_add_shares_outstanding"),
        ("analysis", "0003_tenkinsight"),
    ]

    operations = [
        migrations.CreateModel(
            name="ValuationJournalEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entry_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="작성일"
                    ),
                ),
                (
                    "thesis",
                    models.TextField(
                        help_text="이번 투자 판단의 핵심 논리", verbose_name="투자 가설"
                    ),
                ),
                (
                    "catalysts",
                    models.TextField(blank=True, null=True, verbose_name="주요 촉매"),
                ),
                (
                    "risks",
                    models.TextField(blank=True, null=True, verbose_name="주요 리스크"),
                ),
                (
                    "current_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="현재가"
                    ),
                ),
                (
                    "my_fair_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="내가 생각하는 적정가",
                    ),
                ),
                (
                    "expected_return",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="퍼센트(%) 단위",
                        max_digits=5,
                        null=True,
                        verbose_name="기대 수익률",
                    ),
                ),
                (
                    "conviction_level",
                    models.PositiveSmallIntegerField(
                        default=3,
                        help_text="1(낮음) ~ 5(매우 높음)",
                        verbose_name="확신도",
                    ),
                ),
                (
                    "mate_snapshot",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="작성 시점의 네 메이트 적정가 및 괴리율",
                        verbose_name="메이트 적정가 스냅샷",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="추가 메모"),
                ),
                (
                    "review_on",
                    models.DateField(
                        blank=True, null=True, verbose_name="재검토 예정일"
                    ),
                ),
                (
                    "target_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="목표 매도가",
                    ),
                ),
                (
                    "exit_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="실제 청산 가격",
                    ),
                ),
                (
                    "exit_notes",
                    models.TextField(blank=True, null=True, verbose_name="청산 메모"),
                ),
                (
                    "is_closed",
                    models.BooleanField(default=False, verbose_name="종료 여부"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="valuation_journal_entries",
                        to="stocks.stock",
                    ),
                ),
            ],
            options={
                "verbose_name": "밸류에이션 저널",
                "verbose_name_plural": "밸류에이션 저널",
                "db_table": "valuation_journal_entries",
                "ordering": ["-entry_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["stock", "-entry_date"],
                        name="valuation_j_stock_i_329256_idx",
                    ),
                    models.Index(
                        fields=["is_closed"], name="valuation_j_is_clos_0afe31_idx"
                    ),
                ],
            },
        ),
    ]
