# Generated by Django 4.2.11 on 2025-11-06 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="stripe_customer_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Stripe 고객 ID"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="stripe_subscription_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Stripe 구독 ID"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="subscription_status",
            field=models.CharField(
                blank=True,
                help_text="active, canceled, past_due, etc.",
                max_length=50,
                null=True,
                verbose_name="구독 상태",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="membership_tier",
            field=models.CharField(
                choices=[
                    ("free", "Free"),
                    ("standard", "Standard"),
                    ("premium", "Premium"),
                ],
                default="free",
                max_length=20,
                verbose_name="멤버십 등급",
            ),
        ),
    ]
