# Generated by Django 4.2.11 on 2025-11-03 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stock_code",
                    models.CharField(
                        db_index=True,
                        max_length=20,
                        unique=True,
                        verbose_name="종목 코드",
                    ),
                ),
                ("stock_name", models.CharField(max_length=200, verbose_name="종목명")),
                (
                    "stock_name_en",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="종목명(영문)",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        choices=[("kr", "한국"), ("us", "미국")],
                        default="kr",
                        max_length=10,
                        verbose_name="국가",
                    ),
                ),
                (
                    "exchange",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="거래소"
                    ),
                ),
                (
                    "corp_code",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="기업 코드"
                    ),
                ),
                (
                    "industry",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="산업"
                    ),
                ),
                (
                    "sector",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="섹터"
                    ),
                ),
                (
                    "toss_code",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="토스 코드"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="기업 설명"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성화")),
            ],
            options={
                "verbose_name": "종목",
                "verbose_name_plural": "종목",
                "db_table": "stocks",
            },
        ),
        migrations.CreateModel(
            name="StockPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True, verbose_name="일자")),
                (
                    "open_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, null=True, verbose_name="시가"
                    ),
                ),
                (
                    "high_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, null=True, verbose_name="고가"
                    ),
                ),
                (
                    "low_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, null=True, verbose_name="저가"
                    ),
                ),
                (
                    "close_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="종가"
                    ),
                ),
                ("volume", models.BigIntegerField(null=True, verbose_name="거래량")),
                (
                    "market_cap",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="시가총액"
                    ),
                ),
                (
                    "shares_outstanding",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="발행주식수"
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="stocks.stock",
                    ),
                ),
            ],
            options={
                "verbose_name": "주가 데이터",
                "verbose_name_plural": "주가 데이터",
                "db_table": "stock_prices",
            },
        ),
        migrations.CreateModel(
            name="StockFinancialRaw",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("disclosure_year", models.IntegerField(verbose_name="공시 연도")),
                ("disclosure_quarter", models.IntegerField(verbose_name="공시 분기")),
                ("disclosure_date", models.DateField(verbose_name="공시일")),
                (
                    "revenue",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="매출액"
                    ),
                ),
                (
                    "operating_profit",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="영업이익"
                    ),
                ),
                (
                    "net_income",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="순이익"
                    ),
                ),
                (
                    "ocf",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="영업활동 현금흐름 (OCF)"
                    ),
                ),
                (
                    "icf",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="투자활동 현금흐름"
                    ),
                ),
                (
                    "fcf",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="잉여현금흐름 (FCF)"
                    ),
                ),
                (
                    "capex",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="설비투자 (CAPEX)"
                    ),
                ),
                (
                    "total_assets",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="총자산"
                    ),
                ),
                (
                    "current_assets",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="유동자산"
                    ),
                ),
                (
                    "current_liabilities",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="유동부채"
                    ),
                ),
                (
                    "total_liabilities",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="총부채"
                    ),
                ),
                (
                    "total_equity",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="자본총계"
                    ),
                ),
                (
                    "dividend",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="배당금"
                    ),
                ),
                (
                    "data_source",
                    models.CharField(max_length=50, verbose_name="데이터 소스"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financials_raw",
                        to="stocks.stock",
                    ),
                ),
            ],
            options={
                "verbose_name": "재무 원본 데이터",
                "verbose_name_plural": "재무 원본 데이터",
                "db_table": "stock_financial_raw",
            },
        ),
        migrations.AddIndex(
            model_name="stock",
            index=models.Index(fields=["stock_code"], name="stocks_stock_c_fb14da_idx"),
        ),
        migrations.AddIndex(
            model_name="stock",
            index=models.Index(
                fields=["country", "exchange"], name="stocks_country_22643e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockprice",
            index=models.Index(
                fields=["stock", "date"], name="stock_price_stock_i_b1c210_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="stockprice",
            unique_together={("stock", "date")},
        ),
        migrations.AddIndex(
            model_name="stockfinancialraw",
            index=models.Index(
                fields=["stock", "disclosure_date"],
                name="stock_finan_stock_i_16d03a_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="stockfinancialraw",
            unique_together={("stock", "disclosure_year", "disclosure_quarter")},
        ),
    ]
