# Generated by Django 4.2.11 on 2025-11-07 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="cik",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=20,
                null=True,
                verbose_name="CIK 번호",
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="shares_outstanding",
            field=models.BigIntegerField(
                blank=True, null=True, verbose_name="발행 주식 수"
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="shares_outstanding_updated_at",
            field=models.DateField(
                blank=True, null=True, verbose_name="주식수 업데이트일"
            ),
        ),
    ]
