# Generated by Django 4.2.8 on 2025-11-05 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField(verbose_name='매수일')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='매수가')),
                ('shares', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='보유 수량')),
                ('memo', models.TextField(blank=True, help_text='왜 샀는지, 투자 이유 등', null=True, verbose_name='메모')),
                ('sell_criteria', models.JSONField(blank=True, help_text='예: FCF 2분기 연속 10% 감소', null=True, verbose_name='매도 기준')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('is_sold', models.BooleanField(default=False, verbose_name='매도 완료')),
                ('sold_date', models.DateField(blank=True, null=True, verbose_name='매도일')),
                ('sold_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='매도가')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to='stocks.stock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '포트폴리오',
                'verbose_name_plural': '포트폴리오',
                'db_table': 'portfolio',
                'ordering': ['-purchase_date'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(verbose_name='스냅샷 날짜')),
                ('fcf_margin', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='FCF Margin')),
                ('roe', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='ROE')),
                ('debt_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='부채비율')),
                ('current_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='유동비율')),
                ('revenue_growth', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='매출 성장률')),
                ('fcf_growth', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='FCF 성장률')),
                ('total_score', models.IntegerField(blank=True, null=True, verbose_name='총점')),
                ('cashflow_score', models.IntegerField(blank=True, null=True, verbose_name='현금흐름 점수')),
                ('safety_score', models.IntegerField(blank=True, null=True, verbose_name='안전성 점수')),
                ('growth_score', models.IntegerField(blank=True, null=True, verbose_name='성장성 점수')),
                ('raw_indicators', models.JSONField(blank=True, null=True, verbose_name='원본 지표')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('portfolio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='snapshot', to='portfolio.portfolio')),
            ],
            options={
                'verbose_name': '포트폴리오 스냅샷',
                'verbose_name_plural': '포트폴리오 스냅샷',
                'db_table': 'portfolio_snapshot',
            },
        ),
        migrations.CreateModel(
            name='HoldingSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal', models.CharField(choices=[('STRONG_HOLD', '강력 보유'), ('HOLD', '보유'), ('REVIEW', '재검토'), ('CONSIDER_SELL', '매도 고려')], max_length=20, verbose_name='시그널')),
                ('signal_date', models.DateField(verbose_name='시그널 날짜')),
                ('current_fcf_margin', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='현재 FCF Margin')),
                ('current_roe', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='현재 ROE')),
                ('current_debt_ratio', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='현재 부채비율')),
                ('current_score', models.IntegerField(null=True, verbose_name='현재 점수')),
                ('score_change', models.IntegerField(null=True, verbose_name='점수 변화')),
                ('fcf_trend', models.CharField(blank=True, max_length=50, null=True, verbose_name='FCF 추세')),
                ('warnings', models.JSONField(blank=True, null=True, verbose_name='경고 사항')),
                ('recommendation', models.TextField(blank=True, null=True, verbose_name='판단 근거')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='portfolio.portfolio')),
            ],
            options={
                'verbose_name': '보유 판단 시그널',
                'verbose_name_plural': '보유 판단 시그널',
                'db_table': 'holding_signals',
                'ordering': ['-signal_date'],
            },
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['user', 'is_sold'], name='portfolio_user_id_60077f_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['stock'], name='portfolio_stock_i_bfe319_idx'),
        ),
        migrations.AddIndex(
            model_name='holdingsignal',
            index=models.Index(fields=['portfolio', 'signal_date'], name='holding_sig_portfol_cc3df0_idx'),
        ),
    ]
